//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _46612r_MS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int IDProduct { get; set; }
        public int UserID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
